services:
  db:
    image: postgres:16
    env_file: [ env.example ]
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  manager:
    build:
      context: .
      dockerfile: build/Dockerfile.manager
    env_file: [ env.example ]
    ports: ["8080:8080"]
    depends_on: [db]

volumes:
  dbdata:
