services:
  db:
    image: postgres:16
    env_file: [ env.example ]
    ports: ["5432:5432"]
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: build/Dockerfile.api
    env_file: [ env.example ]
    environment:
      - DATABASE_URL=${KUBENOVA_DB_URL}
    ports: ["8080:8080"]
    depends_on: [db]

volumes:
  dbdata:
