image:
  repository: ghcr.io/vaheed/kubenova/manager
  tag: dev
  pullPolicy: IfNotPresent

env:
  KUBENOVA_REQUIRE_AUTH: "true"
  AGENT_IMAGE: ghcr.io/vaheed/kubenova/agent:dev
  MANAGER_URL_PUBLIC: http://kubenova-manager.kubenova-system.svc.cluster.local:8080
  CAPSULE_PROXY_URL: https://capsule-proxy.capsule-system.svc
