apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenova-manager
  labels: { app: kubenova-manager }
spec:
  replicas: 1
  selector:
    matchLabels: {app: kubenova-manager}
  template:
    metadata:
      labels: {app: kubenova-manager}
    spec:
      securityContext:
        runAsNonRoot: true
      containers:
        - name: manager
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          env:
            - name: KUBENOVA_REQUIRE_AUTH
              value: "{{ .Values.env.KUBENOVA_REQUIRE_AUTH }}"
            - name: AGENT_IMAGE
              value: "{{ .Values.env.AGENT_IMAGE }}"
            - name: MANAGER_URL_PUBLIC
              value: "{{ .Values.env.MANAGER_URL_PUBLIC }}"
            - name: CAPSULE_PROXY_URL
              value: "{{ .Values.env.CAPSULE_PROXY_URL }}"
            - name: DEFAULT_NS_RESOURCEQUOTA
              value: "{{ .Values.env.DEFAULT_NS_RESOURCEQUOTA | default "" }}"
            - name: DEFAULT_PROJECT_QUOTA
              value: "{{ .Values.env.DEFAULT_PROJECT_QUOTA | default "" }}"
          readinessProbe:
            httpGet: { path: /healthz, port: 8080 }
            initialDelaySeconds: 3
            periodSeconds: 5
