{{- if and (not .Values.jwt.existingSecret) .Values.jwt.value }}
apiVersion: v1
kind: Secret
metadata:
  name: kubenova-manager-jwt
  labels:
    app: kubenova-manager
type: Opaque
stringData:
  {{ .Values.jwt.key | default "JWT_SIGNING_KEY" }}: {{ .Values.jwt.value | quote }}
{{- end }}

