blank_issues_enabled: false
contact_links:
  - name: Security reports
    url: https://github.com/vaheed/kubenova/security/advisories
    about: Please use GitHub security advisories or other private channels for reporting security vulnerabilities.

