apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsule-proxy
  labels:
    app: capsule-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capsule-proxy
  template:
    metadata:
      labels:
        app: capsule-proxy
    spec:
      containers:
        - name: capsule-proxy
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep", "3650"]
