image:
  repository: ghcr.io/vaheed/kubenova-api
  tag: dev
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

env:
  KUBENOVA_REQUIRE_AUTH: "true"
  AGENT_IMAGE: ghcr.io/vaheed/kubenova-agent:dev
  MANAGER_URL_PUBLIC: http://kubenova-api.kubenova.svc.cluster.local:8080
