apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenova-agent
rules:
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["namespaces","resourcequotas","roles","rolebindings","networkpolicies","services","deployments","jobs","cronjobs","events"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["capsule.clastix.io"]
    resources: ["tenants","tenantresourcequotas","namespaceoptions"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["core.oam.dev","workflow.vela.io"]
    resources: ["applications","applicationrevisions","workflowruns","componentdefinitions","traitdefinitions","policydefinitions"]
    verbs: ["get","list","watch","create","update","patch","delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenova-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubenova-agent
subjects:
  - kind: ServiceAccount
    name: kubenova-agent
    namespace: kubenova
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubenova-agent
  namespace: kubenova
