image:
  repository: ghcr.io/vaheed/kubenova/agent
  tag: dev
  pullPolicy: IfNotPresent

redis:
  enabled: true
  image: redis:7
  addr: redis:6379

manager:
  url: http://kubenova-api.kubenova.svc.cluster.local:8080
  batchIntervalSeconds: 10
  batchMaxItems: 100
