apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubenova-system
resources:
  - serviceaccount.yaml
  - role.yaml
  - rolebinding.yaml
  - role-secrets.yaml
  - rolebinding-secrets.yaml
  - deployment.yaml
