apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenova-operator
rules:
  - apiGroups: [""]
    resources: ["configmaps", "namespaces"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["kubenova.io"]
    resources: ["novatenants", "novaprojects", "novaapps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["kubenova.io"]
    resources: ["novatenants/status", "novaprojects/status", "novaapps/status"]
    verbs: ["get", "patch", "update"]
