apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubenova-operator-secrets
subjects:
  - kind: ServiceAccount
    name: kubenova-operator
    namespace: kubenova-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubenova-operator-secrets
