apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubenova-operator
rules:
  - apiGroups: [""]
    resources:
      - configmaps
      - namespaces
      - events
      - serviceaccounts
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings", "clusterroles", "clusterrolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["apiregistration.k8s.io"]
    resources: ["apiservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["admissionregistration.k8s.io"]
    resources:
      - validatingwebhookconfigurations
      - mutatingwebhookconfigurations
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["core.oam.dev"]
    resources:
      - componentdefinitions
      - traitdefinitions
      - policydefinitions
      - workflowstepdefinitions
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["capsule.clastix.io"]
    resources:
      - capsuleconfigurations
      - tenants
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["kubenova.io"]
    resources: ["novatenants", "novaprojects", "novaapps"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["kubenova.io"]
    resources: ["novatenants/status", "novaprojects/status", "novaapps/status"]
    verbs: ["get", "patch", "update"]
