apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubenova-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubenova-agent
subjects:
  - kind: ServiceAccount
    name: kubenova-agent
    namespace: kubenova-system
