apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["", "apps", "batch", "networking.k8s.io"]
    resources: ["namespaces","resourcequotas","roles","rolebindings","networkpolicies","services","deployments","jobs","cronjobs","events","configmaps"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["capsule.clastix.io"]
    resources: ["tenants","tenantresourcequotas","namespaceoptions"]
    verbs: ["get","list","watch","create","update","patch","delete"]
  - apiGroups: ["core.oam.dev","workflow.vela.io"]
    resources: ["applications","applicationrevisions","workflowruns","componentdefinitions","traitdefinitions","policydefinitions"]
    verbs: ["get","list","watch","create","update","patch","delete"]
