apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-leader-election
  namespace: kubenova-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-leader-election
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: kubenova-system

