apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tenant-discovery-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tenant-discovery
subjects:
  - kind: Group
    name: tenant-admins
  - kind: Group
    name: tenant-maintainers

