apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent
  labels: { app: agent }
spec:
  replicas: 2
  selector:
    matchLabels: {app: agent}
  template:
    metadata:
      labels: {app: agent}
    spec:
      securityContext:
        runAsNonRoot: true
      serviceAccountName: agent
      containers:
        - name: agent
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
          readinessProbe:
            httpGet: { path: /healthz, port: 8082 }
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet: { path: /readyz, port: 8082 }
            initialDelaySeconds: 10
            periodSeconds: 10
          env:
            - name: MANAGER_URL
              value: "{{ .Values.manager.url }}"
            - name: BATCH_INTERVAL_SECONDS
              value: {{ .Values.manager.batchIntervalSeconds | quote }}
            - name: CAPSULE_VERSION
              value: {{ .Values.bootstrap.capsuleVersion | quote }}
            - name: CAPSULE_PROXY_VERSION
              value: {{ .Values.bootstrap.capsuleProxyVersion | quote }}
            - name: VELA_CORE_VERSION
              value: {{ .Values.bootstrap.velaCoreVersion | quote }}
            - name: REDIS_ADDR
              value: "{{ .Values.redis.addr }}"
            - name: BATCH_MAX_ITEMS
              value: {{ .Values.manager.batchMaxItems | quote }}
        {{- if .Values.redis.enabled }}
        - name: redis
          image: "{{ .Values.redis.image }}"
          args: ["--save", "", "--appendonly", "no"]
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
        {{- end }}
