apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: agent-leader-election
  namespace: kubenova-system
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: agent-leader-election
  namespace: kubenova-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: agent-leader-election
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: kubenova-system

