apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: [""]
    resources: ["namespaces","configmaps","events"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get","list","watch","create"]
  - apiGroups: ["capsule.clastix.io"]
    resources: ["tenants"]
    verbs: ["get","list","watch","create","update","patch"]
  - apiGroups: ["core.oam.dev"]
    resources: ["applications"]
    verbs: ["get","list","watch","create","update","patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agent
subjects:
  - kind: ServiceAccount
    name: agent
    namespace: kubenova-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent
  namespace: kubenova-system
