apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "operator.name" . }}-secrets
  labels:
    {{- include "operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "operator.name" . }}-secrets
