image:
  repository: ghcr.io/vaheed/kubenova/agent
  tag: dev
  pullPolicy: Always

redis:
  enabled: true
  image: redis:7
  addr: redis:6379

manager:
  url: http://kubenova-manager.kubenova.svc.cluster.local:8080
  batchIntervalSeconds: 10
  batchMaxItems: 100

bootstrap:
  capsuleVersion: 0.10.6
  capsuleProxyVersion: 0.9.13
  velaCoreVersion: ""
