apiVersion: apps/v1
kind: Deployment
metadata:
  name: vela-core
  labels:
    app: kubevela
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevela
  template:
    metadata:
      labels:
        app: kubevela
    spec:
      containers:
        - name: kubevela
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["sleep", "3650"]
